### ISSUE TITLE
電子レンジが欲しい

### ISSUE THREAD

**Issue by nikezono** [masuilab/todo#1]
デルタにも電子レンジが欲しい

**Comment by shokai** [comment]
:+1:

**Comment by nekobato** [comment]
:+1:

**Comment by shokai** [comment]
安いのでいい
あと皿と箸もすこしほしい

**Comment by ytanaka-** [comment]
:+1:

**Comment by nekobato** [comment]
#3 と関連して、タウのIDP電子レンジを移動すればよいのでは

**Comment by napo0703** [comment]
![](http://i.gyazo.com/18892f2e2b5987e0203db1c760f119f0.png)

**Comment by nikezono** [comment]
[![](http://tiqav.com/4E.th.jpg)](http://tiqav.com/4E)

**Comment by shokai** [comment]
![LGTM](http://www.lgtm.in/p/Uwi3gecZp)
