### ISSUE TITLE
Slackの流れが速すぎる

### ISSUE THREAD

**Issue by nikezono** [masuilab/todo#10]
何か、Slack上で流れた重要な情報をストック情報に変換する仕組みがあるといいのですけど。
たとえば、誰かがStarを付けた発言をまとめて保存しといて、どこからか見れるサービスがあるといいですね。

もしくは課金するとか

**Comment by masui** [comment]
osusumeに貼っておけばいいのでは?

**Comment by nikezono** [comment]
osusumeチャンネルも含めて、流されることがあると思います。
我々の触れるデータベースに保存しておいたほうがいいかなと・・・

**Comment by shokai** [comment]
[Slackの検索機能を強化するSSlackをリリースしました - WebPay Engineering Blog](http://engineering.webpay.co.jp/2014/08/29/release-sslack/)

これはoutgoing webhookでslackの発言を全部貯めて、elasticksearchで検索できるようにしてます
ただoutgoing webhook追加しようにもこれ以上integration追加するには課金が必要です

**Comment by masui** [comment]
Gyazzのosusumeのことなんですが...
http://gyazz.masuilab.org/osusume

**Comment by nikezono** [comment]
すみません、チャンネルのことだと思っていました。
保存先はDBでもGyazzでも問題ないですね。

**Comment by shokai** [comment]
osusumeに貼れる人ってそもそもオススメできるほどにslack全部読めてるわけだから、自分がosusumeに貼るメリット無いんじゃないですか？

**Comment by masui** [comment]
他人のために貼ってあげられないすか

**Comment by nikezono** [comment]
http://shokai.org/blog/archives/9612

で（僕は）満足しました.

また問題意識感じた人は建てるなりReopenしてください.

**Comment by nikezono** [comment]
thanks @shokai :wave:

**Comment by shokai** [comment]
https://github.com/masuilab/slack-hubot/issues/37 でstarを保存して検索できるようにする予定
