### ISSUE TITLE
イオタが汚い

### ISSUE THREAD

**Issue by nekobato** [masuilab/todo#21]
![](http://gyazo.com/10baf5d16a8b5ffa9b88cc445de5ac1b.png)
![](http://tiqav.com/2SN.jpg)

**Comment by nekobato** [comment]
あと流しはおばさんが片付けるわけではなく、善意の妖精さんが片付けているので
流しに物の置きっぱなしはやめましょう

**Comment by Hikaru-Ito** [comment]
学部1年生を中心に年末大掃除したいとおもいます
とりあえずソファなんとかしたいですね

**Comment by TakumiBaba** [comment]
ついでに鍋しよう

**Comment by Hikaru-Ito** [comment]
今週しかなさそうですね
木曜日にでもやりますか

**Comment by Hikaru-Ito** [comment]
掃除完了
