### ISSUE TITLE
DEIM2015に投稿する

### ISSUE THREAD

**Issue by ytanaka-** [masuilab/todo#27]
http://db-event.jpn.org/deim2015/

2014年12月19日(金):発表申込締切
2015年1月9日(金):閲読用予稿論文締切

**Comment by masui** [comment]
インタラクションでもいいと思うけどDEIMもイイネ

**Comment by ytanaka-** [comment]
採録の通知が来ましたので、今後の予定を書いておきます。

2015年2月13日(金):予稿集論文締切
2015年3月2日(月)～4日(水):DEIMフォーラム2015
2015年3月20日(金):最終論文締切

**Comment by ytanaka-** [comment]
http://db-event.jpn.org/deim2015/
参加登録の受付が始まったみたいです
