### ISSUE TITLE
タウ物品整理

### ISSUE THREAD

**Issue by TakumiBaba** [masuilab/todo#3]
今年度終わりにタウ・ロフトから一時撤退しなくてはいけないので、
タウ・ロフトの中の有用なものを選別してイオタ / デルタに移送しなくてはいけない

**Comment by TakumiBaba** [comment]
有用そうなもの(高そうなもの)
適当に追加していってください
- Thunderbolt Display
- テレビ
- ポット
- パソコン
- ディスプレイ(5台ぐらいあった気がする)
- ARDrone

**Comment by nekobato** [comment]
ディスプレイが余り気味なので古いやつを整理しましょう

**Comment by TakumiBaba** [comment]
2月20日から工事が始まるらしいので、2月半ばまでには撤退する必要がありそう

**Comment by TakumiBaba** [comment]
こんなメール来てた。

---

こんにちは。LRWGの原です。
連絡が遅くなり申し訳ありません。スケジュールに関して、新しいものが漸く決
まりましたので、ご案内します。

○今後のスケジュール
1月25日　第一次ロフト利用申請の最終締め切り
1月28日　段ボール1200箱、τに到着。各プログラムに配布しますので、受け取り
に来てください。
1月30日　τ32の貸切開始。梱包した荷物を運び込みます。
2月1日　   τ21の貸切開始
2月2日　　τ1階のギャラリーの貸切開始
2月3日　　τ22の貸切開始
2月19日　2階撤収作業及び3階掃除作業の完了
2月20日　2階工事開始。3階再配置開始。
3月27日　2階工事完了予定

現在まで連絡の対象とされているのは、修士課程、博士課程、上席所員（訪
問）、特任教員です。
管財では、上席所員（訪問）、特任教員の占有利用を取りやめる方針でした。
しかし上席所員・特任教員が修士・博士の研究指導に関与している事、博士候補
が上席所員に登録している事、其の他SFC教員が席を用意する事 もできずプロ
ジェクト要員として雇用している状況を鑑みて、原より継続しての利用を訴状し
ました。
現在、中村さんと徳田さんが議論しているとの事です。

○居場所の無く放浪し、研究の質が下がる事が予想される研究室
BI 冨田・黒田・内藤研3名
CI 加藤研1名
PS 花田研1名　玉村研2名
GR 奥田研2名　廣瀬研1名　神保研1名　加茂研１名
EG 一ノ瀬研3名　厳研1名

席の割り当てに関して、全体メールに対して返信されてきた人に対応しています。
ロフトリニューアルに関して、1月18日までに57名、その後に3名遅れて連絡があ
り現在63名からの連絡を受け取りました。

次回、最終締め切りとする25日には、原と各プログラム再編成代表に送り、その
後席の配分を行い決定します。

現在三階には132席が用意され、その他に本棚、研究資材、共有スペース等が配
置されています。
これまでの申請状況では、7プログラムからの利用を考慮しても、それぞれに余
剰分の席を準備できる予定です。

○再配置に関する各プログラムの調整責任者、及び第一次ロフト利用最終申請の
送り先（敬称略）
BI　  古川    lunarphantom_of_lightlessnight@yahoo.co.jp
CB　松本
CI　　竹之内    takenouc@gmail.com
EG　 原        satty@sfc.keio.ac.jp
GR　野原        naomichi@sfc.keio.ac.jp
HC　寺本    eljauhal@sfc.keio.ac.jp
PS　 オスマン    othman@sfc.keio.ac.jp

どうぞよろしくお願いいたします。
…

**Comment by nekobato** [comment]
集まって撤退しましょう

## ダメな日
- @nekobato
  - [ ] 02-09
  - [ ] 02-10
  - [ ] 02-11
  - [ ] 02-12
  - [x] 02-13
  - [ ] 02-14
  - [ ] 02-15
- @TakumiBaba 
  - [x] 02-09
  - [x] 02-10
  - [ ] 02-11
  - [ ] 02-12
  - [x] 02-13
  - [ ] 02-14
  - [ ] 02-15
- @marutaru 
  - [ ] 02-09
  - [ ] 02-10
  - [ ] 02-11
  - [ ] 02-12
  - [ ] 02-13
  - [ ] 02-14
  - [ ] 02-15
- @ytanaka- 
  - [x] 02-09
  - [ ] 02-10
  - [ ] 02-11
  - [ ] 02-12
  - [x] 02-13
  - [ ] 02-14
  - [ ] 02-15
- @keroxp 
  - [ ] 02-09
  - [ ] 02-10
  - [ ] 02-11
  - [ ] 02-12
  - [ ] 02-13
  - [ ] 02-14
  - [ ] 02-15
- @nikezono 
  - [ ] 02-09
  - [x] 02-10
  - [ ] 02-11
  - [ ] 02-12
  - [x] 02-13
  - [ ] 02-14
  - [ ] 02-15

**Comment by nekobato** [comment]
02/11にやりますので院生各位はご参集ください

**Comment by nikezono** [comment]
終わった
