### ISSUE TITLE
デルタのドアのRaspberry Piが死んだ

### ISSUE THREAD

**Issue by napo0703** [masuilab/todo#31]
電源入れ直しても動かない。
電源のmicroUSBケーブル挿すと赤いLEDの他に黄や緑のLEDも点滅するはずだけど点滅しないです。

**Comment by isSatake** [comment]
SDが死んでるという可能性もあるかと

**Comment by napo0703** [comment]
SDカードが死んだっぽいです。Raspbian入れなおします。
デルタのドア開けと温度/明るさは今使えません。

**Comment by napo0703** [comment]
( ﾟ皿ﾟ)あああああああ
コンデンサ取れたああああああ
![](http://i.gyazo.com/2e8129fa92a343f9ed23318204214d86.png)

**Comment by napo0703** [comment]
これを機にコンデンサを大容量のものに変更しよう。
http://d.hatena.ne.jp/lycoris_blog/20140221/1392964368
土日にコンデンサ買ってきます。

**Comment by napo0703** [comment]
![](http://i.gyazo.com/f5793d5829a4b7011a8867281502a184.png)

**Comment by napo0703** [comment]
16V220μFのコンデンサから16V460μFのに交換した。
USB機器を接続しても電源が落ちない。快適！

**Comment by shokai** [comment]
依然死んでる

**Comment by napo0703** [comment]
![](http://blog-imgs-47.fc2.com/i/m/o/imokoonono/c0141933_22242891.jpg)

**Comment by napo0703** [comment]
Raspberry Piは信用ならんのでMac mini使ってます。
