### ISSUE TITLE
イオタのモニタのアームを探す

### ISSUE THREAD

**Issue by isSatake** [masuilab/todo#32]
ORFの後どっかいった

**Comment by sota1235** [comment]
俺の荷物の中にはなかったです

**Comment by isSatake** [comment]
![2015-01-16 15 29 33](https://cloud.githubusercontent.com/assets/5730406/5787959/71d01a30-9e5d-11e4-9554-1c579ae6c4bb.jpg)
モニタが立った！

**Comment by napo0703** [comment]
見つからない

**Comment by napo0703** [comment]
あった
