### ISSUE TITLE
2014年度秋 IDPプロジェクト活動報告書

### ISSUE THREAD

**Issue by nekobato** [masuilab/todo#35]
<English text follows the Japanese text>

政策・メディア研究科修士課程  プロジェクト科目履修者各位

SFC学事担当　升川です。

「プロジェクト活動報告書」をアップロードするための
大学院プロジェクト成果URL登録システムの利用が本日より
可能になりましたので連絡いたします。
今学期プロジェクト科目を履修している修士課程の学生は
以下を確認のうえ、期日までに報告書を作成し、必ず登録してください。

※web登録期間は、12月22日 10:00 ～ 1月21日　23:00までです。
# 

　2014年度秋学期大学院プロジェクト活動報告書作成について

　　　　　　　　　　　　　　　　　　　 政策・メディア研究科
　　　　　　　　　　　　　　　　　　　 委員長　徳田　英幸

今学期政策・メディア研究科修士課程設置のプロジェクト科目を
履修している学生は、webサイトに当該学期中のプロジェクトにおける
個々人の活動の成果を作成・登録してください。

主旨は、政策・メディア研究科が最も重視するコラボレーションの場
であるプロジェクトが如何なるもので、どのような成果が上がったかを
SFC関係者が一目で分かるようにするためのものです。
つきましては、履修者は以下の手続きに従い、準備してください。

注意:
複数のプロジェクト科目を履修している場合はそれぞれのプロジェクトの
成果報告が必要です。また、共同研究であっても成果報告は各自作成ください。

　　　　　　　　　　　　　　　記

1.作成対象者:各プロジェクト科目を履修している修士課程の学生全員
（2015年3月修了予定者も含む）

2.作成期限:2015年1月21日（水）23：00（日本時間）【締切厳守】

3.具体的な流れについて
　a.自分自身のプロジェクト活動報告書（Ａ４・１枚程度）を作成し、
　　web上に公開してください。

```
＊活動報告書のURLは以下のように指定してください。
```

　　  http://web.sfc.keio.ac.jp/~各自CNS(ERNS)ログイン名/???.html
　　 （"?"は任意のファイル名）

```
＊ファイルをweb上に公開する方法は、CNSガイドを参照してください。
```

　　  http://cns-guide.sfc.keio.ac.jp/2014/CNSguide2014.pdf

　b.期日までに、a.で公開した活動報告書のURLを大学院プロジェクト
　　成果URL登録システムに登録してください。

```
＊大学院プロジェクト成果URL登録システム
```

　  　http://it.sfc.keio.ac.jp/m-pro/
     "登録方法"を選択し、CNS(ERNS)ログイン名およびパスワードを
     入力して活動報告書のURLを登録ください。

```
＊このシステムはURLを登録するためのものです。
 アップローダ機能はありませんので、あらかじめWeb上に
 公開した報告書のURLを登録してください。
```

　　※締切前に、登録したプロジェクト活動報告書がきちんと表示されるかどう
　　　か、必ず確認してください。

4.報告書未登録の扱い
プロジェクト活動報告書が未登録の場合、ペナルティとして所属プログラム
への次学期のプログラム費の配分がなされません（未登録者の人数分、
減額されます）。
# 以上

慶應義塾大学 湘南藤沢事務室 学事担当
KEIO SFC Academic Affairs Office
TEL:0466-49-3406
http://www.sfc.keio.ac.jp

**Comment by nikezono** [comment]
- [x] @nekobato 
- [x] @TakumiBaba 
- [x] @ytanaka-
- [x] @marutaru 
- [x] @keroxp 
- [x] @nikezono

終わった人からチェック付けていきましょう

**Comment by nikezono** [comment]
お疲れ様でした。
