### ISSUE TITLE
インタラクションのデモ発表のお手伝い

### ISSUE THREAD

**Issue by shokai** [masuilab/todo#39]
インタラクションのデモ発表で研究室で降臨鉄道を走らせるのでお手伝いいただきたい

created by nikezono & hubot

**Comment by napo0703** [comment]
3/7(土)に研究室にいていただき降臨鉄道から監視されるだけの簡単なお仕事です。
私はインタラクションの会場のでその様子をディスプレイに表示します。
途中でバッテリーの交換などをお願いすることがあるかもしれません。
モノレールが引っかかって止まってしまった時に直していただきたいです。

**Comment by napo0703** [comment]
もちろんボードゲームをしていていただいても構いません。

**Comment by napo0703** [comment]
![](http://i.gyazo.com/a87cba7ddfb1ac5a83f804a3ae0627cc.png)

**Comment by nekobato** [comment]
ヒマかも

**Comment by ytanaka-** [comment]
バッテリーの交換とかは無理ですがたぶん暇なので行きます

**Comment by napo0703** [comment]
![](http://i.gyazo.com/fff8d36dcf2373d3750170e535ecbf36.png)

**Comment by nekobato** [comment]
これって何時から居ればいいんですか

**Comment by napo0703** [comment]
12:00~17:00にいていただきたいです

**Comment by napo0703** [comment]
あ、やっぱり12:00~15:10で大丈夫です

**Comment by napo0703** [comment]
私のインタラクティブ発表は13:00~15:10です。

デルタの机の上ににRaspberry Piとバッテリーが取り付けられたモノレールが置いてあります。
これに横に置いてあるスマートフォンを取り付けて天井のレールに設置していただきたいです。
（本当はRaspberry Piで動画配信をする予定だったのですが、カメラモジュールがぶっ壊れたためやむを得ません。）
モノレールにスマートフォンを取り付ける前に、スマートフォンでIP Webcamというアプリを起動してください。
起動したら一番下の「Start Server」をタップして動画配信を開始します。
カメラの映像が画面に出たらスリープにして構いません。
モノレール側に強力両面テープを貼ってありますのでシールを剥がしてスマートフォンを落ちないようにしっかり取り付けてください。
取り付ける際にはスマートフォンのMicroUSBポートがモノレール中央の側になるようにお願いします。
レールへの取り付けの際は足場が不安定なのでご注意ください。
3時間もないのでバッテリーが切れることは無いとは思いますが、一応替えのバッテリーを用意していますので、もしもの時は交換お願いします。

**Comment by napo0703** [comment]
三行にまとめると

スマートフォンでIP Webcamを起動する
モノレールにスマートフォンと取り付ける
天井のレールに設置する
