### ISSUE TITLE
研究室にひえひえクールブリザードがほしい

### ISSUE THREAD

**Issue by shokai** [masuilab/todo#43]
研究室にひえひえクールブリザードがほしい

created by nikezono & hubot

**Comment by shokai** [comment]
そんなにいいの？

**Comment by ytanaka-** [comment]
結構前に使ってたんですが、かなり良かった気がします

**Comment by shokai** [comment]
これか
[Amazon.co.jp： ELECOM 冷え冷えクールブリザード ノートパソコン冷却台 SX-CL03MSV: パソコン・周辺機器](http://www.amazon.co.jp/exec/obidos/ASIN/B000G1T720/shokai-22)

**Comment by ytanaka-** [comment]
安い割に良い

**Comment by napo0703** [comment]
![](http://i.gyazo.com/3bb4361b1ff0aeab29ee9efe11a30607.png)

**Comment by shokai** [comment]
もうあるっぽいので閉じます
