### ISSUE TITLE
MacProのOSアップデートしてOculusRift用グラボ付ける

### ISSUE THREAD

**Issue by shokai** [masuilab/todo#44]
MacProのOSアップデートしてOculusRift用グラボ付ける

created by shokai & hubot

**Comment by shokai** [comment]
やります

## 注意
- os update中はgyazzが使えなくなる
- homebrewのディレクトリを/usr/local以外に移動、もしくは削除しておかないとosアップデートに物凄い時間がかかるらしい

**Comment by shokai** [comment]
これ日曜にやりますがいいですか

**Comment by nikezono** [comment]
:+1:

**Comment by shokai** [comment]
なんとなく気が向いたので今からやる

**Comment by shokai** [comment]
yosemiteインストール中・・・

**Comment by shokai** [comment]
yosemite入った、videomは何もせず動いてるけどgyazzが起動しない

```
% tail -f /var/log/node-gyazz/node-gyazz.log
env: node: No such file or directory
env: node: No such file or directory
env: node: No such file or directory
```

**Comment by shokai** [comment]
user:masuiで動いているのでPATHいじるわけにもいかないので

```
% ln -s /usr/local/bin/node /bin/node
```

これでなんとかなった

**Comment by shokai** [comment]
なぜかapple IDがnekobato@gmail~~になっている問題

**Comment by shokai** [comment]
解決

**Comment by shokai** [comment]
OculusRift用グラボ付けてなかった

**Comment by shokai** [comment]
nodeを0.10から0.12に上げた

**Comment by shokai** [comment]
![image](https://cloud.githubusercontent.com/assets/34204/8394276/fb9e2efa-1d6a-11e5-958b-17319b8eea31.png)

もう疲れた終わり

**Comment by shokai** [comment]
NVidiaの最新ドライバインストールしろってポップアップが出まくるので、ok押した。
再起動したら有効になるらしいけど、masui先生がログインしていたので再起動してません

適当に誰か再起動して下さい

**Comment by nikezono** [comment]
done.
