### ISSUE TITLE
プロジェクト活動報告書を書く

### ISSUE THREAD

**Issue by napo0703** [masuilab/todo#49]
1.作成対象者:各プロジェクト科目を履修している修士課程の学生全員
（2015年9月修了予定者も含む）

**2.作成期限:2015年7月21日（火）23：00（日本時間）【締切厳守】**

3.具体的な流れについて
　a.自分自身のプロジェクト活動報告書（Ａ４・１枚程度）を作成し、
　　web上に公開してください。

   ＊活動報告書のURLは以下のように指定してください。
　　  http://web.sfc.keio.ac.jp/~各自CNS(ERNS)ログイン名/???.html
　　 （"?"は任意のファイル名）

   ＊ファイルをweb上に公開する方法は、CNSガイドを参照してください。
　　http://cns-guide.sfc.keio.ac.jp/2015/CNSguide2015.pdf

　b.期日までに、a.で公開した活動報告書のURLを大学院プロジェクト
　　成果URL登録システムに登録してください。

   ＊大学院プロジェクト成果URL登録システム
　  　http://it.sfc.keio.ac.jp/m-pro/
    "登録方法"を選択し、CNS(ERNS)ログイン名およびパスワードを
    入力して活動報告書のURLを登録ください。

   ＊このシステムはURLを登録するためのものです。
    アップローダ機能はありませんので、あらかじめWeb上に
    公開した報告書のURLを登録してください。
　　※締切前に、登録したプロジェクト活動報告書がきちんと表示されるかどう
　　　か、必ず確認してください。

4.報告書未登録の扱い
プロジェクト活動報告書が未登録の場合、ペナルティとして所属プログラム
への次学期のプログラム費の配分がなされません（未登録者の人数分、
減額されます）。

以上

**Comment by keroxp** [comment]
リマインダ

**Comment by napo0703** [comment]
![](https://i.gyazo.com/750894731a732881872711d9fc031a2f.png)
