### ISSUE TITLE
防音室がほしい

### ISSUE THREAD

**Issue by napo0703** [masuilab/todo#56]
http://www.danbocchi.com
http://jp.yamaha.com/products/soundproofing/ready-made_rooms/size_08-15/

**Comment by nekobato** [comment]
学校のITC館にある録音ブースじゃダメなんですか（登録めんどいけど

**Comment by napo0703** [comment]
kwsk

**Comment by nekobato** [comment]
http://www.sfc.lib.keio.ac.jp/general/audio.html

**Comment by napo0703** [comment]
![](https://i.gyazo.com/547b016bbd76a6a807a971a2449e654c.png)

**Comment by napo0703** [comment]
![](https://i.gyazo.com/7798dc1e74a59d63d1323564cc159824.png)
