### ISSUE TITLE
開発用のMacBookがほしい

### ISSUE THREAD

**Issue by napo0703** [masuilab/todo#59]
Mac持ってない人が大変そうなので。前みたいに何台かストックしたい。

**Comment by shokai** [comment]
最近linuxインストールおじさんいないんですか

**Comment by napo0703** [comment]
2010年MacBook Airが1台あった。
現在@Hykwtakuminが使ってる。

**Comment by napo0703** [comment]
> 最近linuxインストールおじさんいないんですか

Mac率の上昇に伴っていなくなってしまいました。
環境構築おじさんすら消滅しつつある。
