### ISSUE TITLE
Iota411のMac miniのIPアドレスを固定する

### ISSUE THREAD

**Issue by napo0703** [masuilab/todo#8]

**Comment by shokai** [comment]
というか部屋にグローバルIPアドレスもらった方がいいのでは

**Comment by masui** [comment]
マシンごとに申請するんじゃなかったっけ?

**Comment by masui** [comment]
何に使ってるマシンなんですか

**Comment by napo0703** [comment]
一応イオタのメインマシンです。
ドア開け閉め明るさ温度のArduinoが繋がってます。
http://gyazz.masuilab.org/増井研/Mac%20mini@Iota411

**Comment by shokai** [comment]
deltaみたいにルータに割り振ればいいのでは

**Comment by napo0703** [comment]
はい。ルーターでMac miniにSSHとVNCにポートフォワーディングしているのですが、ルーターに固定のグローバルIPアドレスが割り振られていないので、しばらく経ってIPアドレス変わるとアクセスできなくなってしまいます。なので固定のIPアドレス欲しいです。

**Comment by masui** [comment]
申請しましょう
ルータに固定IPなんてできたっけ?

**Comment by shokai** [comment]
deltaでやってます
普通にどのルータにもある機能です

**Comment by masui** [comment]
いや、申請できるのかという話です

**Comment by shokai** [comment]
できます

**Comment by masui** [comment]
やらなきゃ

**Comment by nikezono** [comment]
イオタ消滅するらしいのでclose
