### ISSUE TITLE
2014年度プロジェクト費で何かを買う

### ISSUE THREAD

**Issue by TakumiBaba** [masuilab/todo#9]
そろそろ使い道を考え始めましょう
ちなみに一人10万*7人なので、70万のはずです。

http://gyazz.masuilab.org/増井研/プログラム費使用方法

**Comment by marutaru** [comment]
スマートウォッチ欲しい

**Comment by napo0703** [comment]
Oculus Riftを快適に使うためにグラボが欲しいです

**Comment by nikezono** [comment]
https://github.com/masuilab/todo/issues/9#issuecomment-64412544

👍

**Comment by TakumiBaba** [comment]
wiss費用をプロジェクト費でお願いします
(個人利用の5万じゃないやつで)

**Comment by keroxp** [comment]
全然思いつかない

**Comment by nekobato** [comment]
これ使いたい人はどんどん物品名と値段書いていきましょう

個人利用：５万
プロジェクト用：５ \* 院生.length 万

**Comment by keroxp** [comment]
買いたい
nexus5: 46080円

**Comment by shokai** [comment]
- blendmicro 10個 38,627円
- blendmicro 2個 9,284円
- 電子部品色々 1,825円
- 合計 49,736円

**Comment by masui** [comment]
リストにできないの?

**Comment by TakumiBaba** [comment]
WISS参加費&宿泊費 37,000円
WISS交通費 15,520円
合計 52,520円

**Comment by TakumiBaba** [comment]
ちなみに通話が可能な端末を買うときは色々と面倒になってた気がします

**Comment by TakumiBaba** [comment]
個人利用は
- RICOH デジタルカメラ RICOH THETA m15 ブルー 360°全天球イメージ撮影デバイス  31,230円
- Philips Friends of hue(フレンズ オブ ヒュー) LightStrips (ライトリボン・シングル) 10950
- ハイパフォーマンス ブラウザネットワーキング――ネットワークアプリケーションのためのパフォーマンス最適化 4,320
- SF映画で学ぶインタフェースデザイン アイデアと想像力を鍛え上げるための141のレッスン 3,456

合計 49,956円

の予定です

**Comment by nekobato** [comment]
個人利用

```
1. Philips hue(ヒュー) スターターセット     ￥ 26,740
2. Jawbone UP24                         ￥ 15,735
3. ヤザワ スポットライトショート クローム * 3 ￥ 2,382
4. ヤザワ ライティングダクトレール           ￥ 2,654
```

計：￥ 47,511

**Comment by shokai** [comment]
誰かoculus rift用のグラボ買ってあげて

**Comment by marutaru** [comment]
個人利用
1. モトローラ Moto 360 Watch スマートウォッチ Android Wear カラー：ストーンレザー ￥ 38384

**Comment by TakumiBaba** [comment]
全体の残りが35万ぐらいになってたので、この金額を使うようにしましょう

**Comment by shokai** [comment]
一応、個人利用っていうか個人判断ですぐ買っていいという意味で、別に個人で使う物だけを買うってのではなかったと思います（個人でしか使えないものを買ってはいけないという意味ではない）

**Comment by shokai** [comment]
http://gyazz.masuilab.org/増井研/プログラム費使用方法

**Comment by ytanaka-** [comment]
DEIM参加費&宿泊費 36,600円
DEIM交通費 16,220円
合計 52,820円

**Comment by ytanaka-** [comment]
個人利用
1. パターン認識と機械学習 上 ￥7,020
2. これなら分かる最適化数学―基礎原理から計算手法まで ￥3,132
合計：￥10,152

**Comment by TakumiBaba** [comment]
2月27日まで

**Comment by shokai** [comment]
これもうとりあえず申請していいですか
27日ジャストに出さなければならないわけではないので

**Comment by marutaru** [comment]
約35万ー約4万(38384)=約31万
買ったのは上に書いてあるmoto360
残り１万は寄付しまふ

**Comment by ytanaka-** [comment]
約31万ー約6万(62972)=約25万

**Comment by nikezono** [comment]
Ocurus Lift DK2(350$)で明日申請します。
約25万 - 約4万 = 約21万

残り1万は要らないので元気玉でグラボにして欲しい所存です（どれ買えばいいのかわからない）

**Comment by napo0703** [comment]
GeForce GTX750Tiはどうでしょうか？
http://kakaku.com/item/K0000634723/
http://planet-green.com/archives/217

**Comment by TakumiBaba** [comment]
グラボ買うならそろそろ買っておかないと、金曜日に間に合わないのでは

**Comment by shokai** [comment]
Macproで使うんだっけ？これ刺さるんだっけ？

**Comment by shokai** [comment]
MacproのVGAがどれがいいかとかは #40 でやりましょう

**Comment by nekobato** [comment]
研究室ルータ + Hueで申請予定
約21万 - 約4万 = 約17万
のこり1万はまだ決めてないです

**Comment by TakumiBaba** [comment]
WISS旅費申請済みです。
申請済みで計算すると
21万 - 5万(WISS旅費) = 残り16万
nekobato申請分で残り12万？

**Comment by shokai** [comment]
申請しました
- 16万 - 49736円 = 残り約11万
- nekobato申請分で残り7万？

**Comment by nekobato** [comment]
申請済みです
残り７万
なんか買いましょう

**Comment by shokai** [comment]
やりました

## 合計21128円
- 工具類：4670円
- 本1冊：1598円
- 本7冊：14860円

**Comment by TakumiBaba** [comment]
反省 もっと早くから申請しよう、残り金額をちゃんと把握しておこう
